server:
    port: 3005
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
      enabled: true
# set file base memory so data will not lost when application restart
#spring.datasource.url=jdbc:h2:file:/data/demo

